### ISSUE TITLE
Nomenclature of incursion severity

### ISSUE THREAD

**Issue by meztez** [bcgov/flight-path-monitoring#11]
How would you name the incursion zones?

Let's say directly in the habitat areas below the altitude tolerance?
The first buffer zone around the original area?
The second buffer zone.

The code currently uses:
https://github.com/bcgov/flight-path-monitoring/blob/eb264baea8204e65c471e8b05045f998fac8a8a4/py/flightPathAnalysis_uwr.py#L399

We will use that for now.

**Comment by kmaricle** [comment]
I think "In UWR", "High", "Moderate" , and "Low" are good
