### ISSUE TITLE
Prepare to include TRACKS database

### ISSUE THREAD

**Issue by meztez** [bcgov/flight-path-monitoring#8]
Since we do not have a database structure just yet, assume the TRACKS will end up as a collection of flights paths?

Treat like a regular flight path file for now.

Once it is transformed into a spatial feature object, the pipeline is the same.

**Comment by meztez** [comment]
~~@kmaricle Do the limited access tracking database have more recent observation than the public one? Latest one in the public one are from 2015.~~

~~Public : https://catalogue.data.gov.bc.ca/dataset/wildlife-species-inventory-telemetry-observations-non-sensitive
Sensitive : https://catalogue.data.gov.bc.ca/dataset/wildlife-species-inventory-telemetry-observations-all~~

~~Auth with bcdata requires an API key.~~
~~https://github.com/bcgov/bcdata/blob/1a78930895669ab3840033a28af2f544061b69c0/README.Rmd#L99~~

Sorry, my comment was meant for the wildlife telemetry issue.

**Comment by kmaricle** [comment]
Hi Bruno et al, Tracks development is paused right now- so the only way to pull in flight data for now will be through manually loading flight data (kmz, gpx, csv). 
When tracks is complete i will likley look to re-hire you guys to merge the two. The telemetry observations will also hopefully get added down the road once BC Telemetry Warehouse is completed.

**Comment by meztez** [comment]
Function `read_flight_db` is ready to be written in `ingest_flights.R` once we have a database connection definition and a data structure.
